parameters:
    # Для запуска Symfony на хосте (Ubuntu vm212)
    ollama_base_url: 'http://127.0.0.1:11434'

services:
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\:
        resource: '../src/Service/*'
        autoconfigure: true
        autowire: true

    App\Service\OllamaService:
        autowire: true
        arguments:
            $ollamaBaseUrl: '%ollama_base_url%'
